package com.techcourse.service;

import com.interface21.dao.DataAccessException;
import com.interface21.jdbc.datasource.DataSourceUtils;
import com.interface21.jdbc.support.SQLExceptionConsumer;
import com.techcourse.config.DataSourceConfig;
import com.techcourse.domain.User;
import java.sql.Connection;
import java.sql.SQLException;
import javax.sql.DataSource;

public class TxUserService implements UserService {

    private final UserService userService;

    public TxUserService(UserService userService) {
        this.userService = userService;
    }

    @Override
    public User findById(long id) {
        return userService.findById(id);
    }

    @Override
    public void insert(User user) {
        userService.insert(user);
    }

    @Override
    public void changePassword(final long id, final String newPassword, final String createBy) {
        DataSource dataSource = DataSourceConfig.getInstance();
        Connection connection = DataSourceUtils.getConnection(dataSource);
        try {
            connection.setAutoCommit(false);
            userService.changePassword(id, newPassword, createBy);
            connection.commit();
        } catch (DataAccessException | SQLException e) {
            rollbackTransaction(connection);
            throw new DataAccessException(e);
        } finally {
            DataSourceUtils.releaseDataSource(dataSource);
        }
    }

    private void rollbackTransaction(Connection connection) {
        SQLExceptionConsumer.execute(() -> {
            connection.rollback();
            return null;
        }, "connection을 rollback하는데 실패했습니다.");
    }
}
